### ISSUE TITLE
Logo For Diary

### ISSUE THREAD

**Issue by zularizal** [SirionRazzer/Diary#1]
Hi @SirionRazzer , I'm a graphic designer. I like your project, I want to contribute by creating a free logo for your project. What do you think?

**Comment by SirionRazzer** [comment]
Hi! I highly appreciate your offer. I can send you some screenshots of the app.

**Comment by zularizal** [comment]
Sorry for late, Can you send some screenshot of the app to me?

**Comment by SirionRazzer** [comment]
@zularizal These are screens that are already finished. I have made s simple logo for the login screen as a placeholder. I would like to use logo as an app icon as well.

![Screenshot_1556010569](https://user-images.githubusercontent.com/12099284/56649371-47a21980-6685-11e9-9081-99b6289fee33.png)
![Screenshot_1556010543](https://user-images.githubusercontent.com/12099284/56649372-47a21980-6685-11e9-949e-8dc0c55fab0f.png)
![Screenshot_1556010563](https://user-images.githubusercontent.com/12099284/56649374-483ab000-6685-11e9-9120-42fee1ac1914.png)

**Comment by zularizal** [comment]
Sorry for a long time, because before I was a little busy in the real world.

This is the design logo for your project. I have designed 3 logo concepts for your project. Which do you like?

If there is something you want to change, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/57206962-051cfd00-6ff4-11e9-9229-16e775b922c7.png)

**Comment by SirionRazzer** [comment]
Thanks for your great designs! I feel the second one has the most "call to action" feeling and is quite unique. Only minor change I would personally like is to center the point of the pen in the shadow below -> pen slicing paper in the halves.

**Comment by zularizal** [comment]
Okay, Do you mean this?

![bitmap](https://user-images.githubusercontent.com/38547278/57346717-d466d000-7179-11e9-9c7d-0dfbd96587bc.png)

**Comment by SirionRazzer** [comment]
Yes, but I can see now that your original design is really better, so I would prefer the original one. I will mention your nickname in the Contributors section of repository's readme. Are you okay with it?

Could you commit 512x512px or svg files? I will use the one color as well for the app's login page.

I hope the app will be ready in a few weeks.

**Comment by zularizal** [comment]
Hi @SirionRazzer , I have sent a pull request for you. #2 

And also I have uploaded the logo to the drive. Check this link.
https://drive.google.com/open?id=197o9gHCpiE0y0Z70c_rmyF05MCO0Hk0E

**Comment by zularizal** [comment]
@SirionRazzer  Do I upload the correct logo?

**Comment by SirionRazzer** [comment]
Yes, you did, thank you very much :)
